Algoritmo "media"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Seção de Declarações das variáveis 
  a,b: inteiro
  m : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Informe dois numeros  inteiros ")
 leia(a)
 
 m <- (a)*3

 escreval("O resultado de ",a," x 3 é igual a ",m,".")

Fimalgoritmo