Algoritmo "media"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Seção de Declarações das variáveis 
  a,b: inteiro
  m : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Informe 1 numero  inteiro ")
 leia(a)
 
 m <- (a)/2

 escreval("O resultado de ",a," dividido por 2 é igual a ",m,".")

Fimalgoritmo