Algoritmo "media"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Seção de Declarações das variáveis 
  a,b: inteiro
  m : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Informe 1 numero  inteiro ")
 leia(a)
 
 m <- (a)/4

 escreval("O resultado de 25% de  ",a," é igual a ",m,".")

Fimalgoritmo