Algoritmo "pc45"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Seção de Declarações das variáveis 
  a,b: real
  m : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Informe 2 numeros  inteiro ")
 leia(a,b)
 
 m <- (a+b)*0.45
 

 escreval("O resultado 45% de  ",a," + ",b," é igual a ",m,".")

Fimalgoritmo