Algoritmo "pc45"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Seção de Declarações das variáveis 
  a,b,c: real
  m : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Informe 3 numeros  inteiros ")
 leia(a,b,c)
 
 m <- D:= A +C - B
 

 escreval("O resultado ",D," é igual  ",m,".")

Fimalgoritmo